version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Starting install
      - yarn install
  build:
    commands:
      - echo Starting build on `date`
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: './'
